export const FIND_USER_LOCATION = 'FIND_USER_LOCATION';
export const SESSION_ADD = 'SESSION_ADD';
export const SET_LOCATION = 'SET_LOCATION';
export const INIT_USER_LOCATION = 'INIT_USER_LOCATION'


export const CALCULATE_DASHBOARD_STATS = 'CALCULATE_DASHBOARD_STATS';
export const INIT_CALC_STATS = 'INIT_CALC_STATS';


export const TOGGLE_SIDEDRAW = 'TOGGLE_SIDEDRAW';
export const CLOSE_SIDEDRAW = 'CLOSE_SIDEDRAW';

export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT ='AUTH_LOGOUT';
export const AUTH_INIT_LOGOUT = 'AUTH_INIT_LOGOUT';
export const AUTH_CHECK_TIMEOUT = 'AUTH_CHECK_TIMEOUT';
export const AUTH_USER = 'AUTH_USER';
export const AUTH_CHECK_STATE = 'AUTH_CHECK_STATE'
