export const FIND_USER_LOCATION = 'FIND_USER_LOCATION';
export const SESSION_ADD = 'SESSION_ADD';
export const SET_LOCATION = 'SET_LOCATION';


export const CALCULATE_DASHBOARD_STATS = 'CALCULATE_DASHBOARD_STATS';

export const TOGGLE_SIDEDRAW = 'TOGGLE_SIDEDRAW';

export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
